services:
  - type: web
    name: trademark-vista
    runtime: python
    rootDirectory: trademarkvista
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trademark-db
          property: connectionString

databases:
  - name: trademark-db
    databaseName: trademark_db
    plan: free